name: "Deploy to Cloud Functions on PR into develop branch "
"on":
  push:
    branches:
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm --prefix ./functions install ./functions
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/593398023204/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-functions-deploy@cubook-dev.iam.gserviceaccount.com"
          create_credentials_file: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"
      - id: "cat_key"
        run: "echo ::set-output name=key::$(cat $GOOGLE_APPLICATION_CREDENTIALS)"
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v11.16.0
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ steps.cat_key.outputs.key }}
          PROJECT_ID: cubook-dev
